version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/*"
      redis:
        patterns:
          - "github.com/redis/*"
          - "github.com/go-redis/*"
    reviewers:
      - "replicate/infra"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
    - "replicate/infra"
