// Code generated by "stringer -type=DetailLevel,SampleMode -output=tracestate_string.go"; DO NOT EDIT.

package telemetry

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DetailLevelDefault-0]
	_ = x[DetailLevelFull-1]
}

const _DetailLevel_name = "DetailLevelDefaultDetailLevelFull"

var _DetailLevel_index = [...]uint8{0, 18, 33}

func (i DetailLevel) String() string {
	if i < 0 || i >= DetailLevel(len(_DetailLevel_index)-1) {
		return "DetailLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DetailLevel_name[_DetailLevel_index[i]:_DetailLevel_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SampleModeNever - -1]
	_ = x[SampleModeDefault-0]
	_ = x[SampleModeAlways-1]
}

const _SampleMode_name = "SampleModeNeverSampleModeDefaultSampleModeAlways"

var _SampleMode_index = [...]uint8{0, 15, 32, 48}

func (i SampleMode) String() string {
	i -= -1
	if i < 0 || i >= SampleMode(len(_SampleMode_index)-1) {
		return "SampleMode(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _SampleMode_name[_SampleMode_index[i]:_SampleMode_index[i+1]]
}
