#!/bin/sh

set -eu

: "${GITHUB_ACTIONS:=}"

cd "$(dirname "$0")"
cd ..

if [ "$GITHUB_ACTIONS" = "true" ]; then
  set -- "$@" --output.text.path --output.text.print-linter-name --output.text.print-issued-lines
fi

go generate ./...
if ! git diff --exit-code >/dev/null; then
  echo "Error: generated code is not up-to-date! Run 'go generate ./...' and update your branch." >&2
  exit 1
fi

exec go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.5 run --output.text.colors "$@"
