#!/bin/sh

set -eu

: "${GITHUB_ACTIONS:=}"

cd "$(dirname "$0")"
cd ..

if [ "$GITHUB_ACTIONS" = "true" ]; then
  set -- "$@" --out-format=colored-line-number
fi

go generate ./...
if ! git diff --exit-code >/dev/null; then
  echo "Error: generated code is not up-to-date! Run 'go generate ./...' and update your branch." >&2
  exit 1
fi

exec go run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.63.4 run "$@"
