#!/bin/sh

set -eu

: "${GITHUB_ACTIONS:=}"

cd "$(dirname "$0")"
cd ..

if [ "$GITHUB_ACTIONS" = "true" ]; then
  REDIS_URL=redis://
  export REDIS_URL
fi

# Run the tests for the entire repository.
#
# You can change what this does by passing paths or other arguments to
# gotestsum. See https://github.com/gotestyourself/gotestsum#documentation
#
exec go run gotest.tools/gotestsum "$@"
