name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      # Run valkey so we can integration test the rate limiter and other Redis-dependent packages
      valkey:
        image: valkey/valkey:8.1-alpine
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
        cache: true
    - name: Build
      run: script/build
    - name: Test
      run: script/test

  lint:
    name: Lint
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
    - run: go mod download
    - name: Lint
      run: script/lint
    - name: Formatting
      run: CHECKONLY=1 script/format
